name: "Workflow Telemetry"
description: "Workflow Telemetry"
author: "Serkan Özal <serkan@thundra.io>"
inputs:
  github_token:
    description: "GitHub API Access Token"
    default: ${{ github.token }}
    required: false
  api_key:
    description: "Foresight API KEY"
    required: true
  stat_frequency:
    description: "Statistic collection frequency in seconds. Must be a number. Defaults to '5'."
    default: 5
    required: false

runs:
  using: "node12"
  main: dist/main/index.js
  post: dist/post/index.js
branding:
  icon: "activity"
  color: "yellow"
